version: "3"

services:
  server:
    build: srv/
    command: python ./srv.py
    ports:
      - 8001:8001
  
  api:
    build: api/
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      - client

  client:
    build: client/
    command: python ./client.py
    network_mode: host
    depends_on:
      - server
      - api



